=== libetl/scrabble/ScrabbleMain/bin/dists/dist.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT DistributionConfiguration (letters)>

<!ELEMENT letter EMPTY >
<!ATTLIST letter
          name CDATA #REQUIRED
          value CDATA #REQUIRED
          number CDATA #REQUIRED>

<!ELEMENT letters ( letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter, letter ) >

=== libetl/scrabble/out/dists/fr_FR.letters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DistributionConfiguration PUBLIC "-//http://libe.toile-libre.org//FR" "dist.dtd">
<letters>
	<letter name="A" value="1" number="9"/>
	<letter name="B" value="3" number="2"/>
	<letter name="C" value="3" number="2"/>
	<letter name="D" value="2" number="3"/>
	<letter name="E" value="1" number="15"/>
	<letter name="F" value="4" number="2"/>
	<letter name="G" value="2" number="2"/>
	<letter name="H" value="4" number="2"/>
	<letter name="I" value="1" number="8"/>
	<letter name="J" value="8" number="1"/>
	<letter name="K" value="10" number="1"/>
	<letter name="L" value="1" number="5"/>
	<letter name="M" value="2" number="3"/>
	<letter name="N" value="1" number="6"/>
	<letter name="O" value="1" number="6"/>
	<letter name="P" value="3" number="2"/>
	<letter name="Q" value="8" number="1"/>
	<letter name="R" value="1" number="6"/>
	<letter name="S" value="1" number="6"/>
	<letter name="T" value="1" number="6"/>
	<letter name="U" value="1" number="6"/>
	<letter name="V" value="4" number="2"/>
	<letter name="W" value="10" number="1"/>
	<letter name="X" value="10" number="1"/>
	<letter name="Y" value="10" number="1"/>
	<letter name="Z" value="10" number="1"/>
	<letter name=" " value="0" number="2"/>
</letters>
