=== libetl/scrabble/out/ui.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT UserInteractionsConfiguration (userinteractions)>

<!ELEMENT userinteractions ((bean | action)*, callback) >

<!ELEMENT bean EMPTY >
<!ATTLIST bean
          name CDATA #REQUIRED
          impl CDATA #REQUIRED>

<!ELEMENT action (listener | timer)* >
<!ATTLIST action
          bean CDATA #REQUIRED
          impl CDATA #REQUIRED>

<!ELEMENT listener EMPTY >
<!ATTLIST listener
          id CDATA #REQUIRED
          type CDATA #REQUIRED
          event CDATA #IMPLIED
          events CDATA #IMPLIED
          method CDATA #REQUIRED>

<!ELEMENT timer EMPTY >
<!ATTLIST timer
          name CDATA #REQUIRED
          delay CDATA #REQUIRED
          method CDATA #REQUIRED>
          
<!ELEMENT callback EMPTY >
<!ATTLIST callback
          impl CDATA #REQUIRED
          method CDATA #REQUIRED>

=== libetl/scrabble/out/interactions/ui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE UserInteractionsConfiguration PUBLIC "-//http://libe.toile-libre.org//FR" "./ui.dtd">
<userinteractions>

 <bean name="gameBean" impl="org.toilelibre.libe.scrabble.applicationlayer.beans.GameBean"/>
 <bean name="newPartyBean" impl="org.toilelibre.libe.scrabble.applicationlayer.beans.party.NewPartyBean"/>
 <bean name="changeTurnBean" impl="org.toilelibre.libe.scrabble.applicationlayer.beans.party.ChangeTurnBean"/>
 
 <action bean="gameBean" impl="org.toilelibre.libe.scrabble.applicationlayer.actions.GameAction">
 	<listener id="sc3d" type="MouseListener" events="pressed, released" method="startStopMove"/>
 	<listener id="sc3d" type="MouseMotionListener" events="moved, dragged" method="updateMousePosition"/>
 	<listener id="sc3d" type="MouseWheelListener" events="wheelMoved" method="forwardBackward"/>
 	<listener id="exitButton" type="ActionListener" event="actionPerformed" method="exit"/>
  	<listener id="newPartyButton" type="ActionListener" event="actionPerformed" method="newParty"/>
  	<listener id="validateButton" type="ActionListener" event="actionPerformed" method="validate"/> 
  	<listener id="skinCbx" type="ActionListener" event="actionPerformed" method="changeSkin"/> 
 	<timer name="movement" delay="0" method="movement"/>
 </action>
 
 <action bean="newPartyBean" impl="org.toilelibre.libe.scrabble.applicationlayer.actions.party.NewPartyAction">
  	<listener id="startNewPartyButton" type="ActionListener" event="actionPerformed" method="execute"/>

 	<timer name="movement" delay="0" method="movement"/>
 </action>

 <action bean="changeTurnBean" impl="org.toilelibre.libe.scrabble.applicationlayer.actions.party.ChangeTurnAction">
 	<timer name="movement" delay="0" method="movement"/>
 	<timer name="movementLetter" delay="1" method="movementLetter"/>
 </action>

 <callback impl="org.toilelibre.libe.scrabble.gui.ScrabbleGUI" method="redirect"/>
</userinteractions>
